drop sequence AREA_SEQ;
drop sequence BRANCH_SEQ;
drop sequence CLIENTS_SEQ;
drop sequence CLIENTSITE_SEQ;
drop sequence COMMENT_SEQ;
drop sequence COURSE_SEQ;
drop sequence EMPLOYEES_SEQ;
drop sequence INCIDENT_SEQ;
drop sequence ORDERS_SEQ;
drop sequence PGROUP_SEQ;
drop sequence PLINE_SEQ;
drop sequence PRODUCT_SEQ;
drop sequence PROMO_SEQ;
drop sequence REGION_SEQ;
drop sequence SESSION_SEQ;
drop sequence TEAMS_SEQ;





DROP TABLE FEEDBACK;
DROP TABLE PROMOSTATE;
DROP TABLE PROMOTIONS;
DROP TABLE PRODUCT_PRICING;
DROP TABLE SUPERVISE_LINES;
DROP TABLE SPECIALIZE;
DROP TABLE VISITLOG;
DROP TABLE ASSIGN_TEAMS_TO_CLIENTS;
DROP TABLE FORM_TEAMS;
DROP TABLE TEAMS;
DROP TABLE REPORT_PROBLEMS;
DROP TABLE PROBLEM_ACTION_ITEMS;
DROP TABLE PROBLEM_COMMENTS;
DROP TABLE PLACE_ORDERS;
DROP TABLE ORDER_DETAILS;
DROP TABLE PRODUCTS;
DROP TABLE TAKE_TRAINING;
DROP TABLE TRAINING_SESSIONS;
DROP TABLE CLIENT_SITES;
ALTER TABLE BRANCHES DROP CONSTRAINT mainbranch_fk;
DROP TABLE MAIN_BRANCHES;
DROP TABLE REGIONS;
DROP TABLE PERSONNEL_MANAGERS;
DROP TABLE SALARY_EMPLOYEES;
DROP TABLE HOURLY_EMPLOYEES;
DROP TABLE PRODLINE_MANAGERS;
DROP TABLE FUNCTIONAL_MANAGERS;
DROP TABLE CSR_EMP;
DROP TABLE PRODUCT_LINES;
DROP TABLE PRODUCT_GROUPS;
DROP TABLE AREAS;
DROP TABLE PROBLEM_INCIDENTS;
DROP TABLE COURSES;
DROP TABLE ORDERS;
DROP TABLE CLIENTS;
DROP TABLE EMPLOYEES;
DROP TABLE BRANCHES;